import { Leaf, Bug, Droplets, Sun, TrendingUp, Handshake, Users } from 'lucide-react';

export const ARTICLES = [
  {
    id: 1, title: 'Teknik Pemupukan Berimbang untuk Padi Sawah', type: 'Artikel', category: 'Pupuk', icon: Leaf, readTime: '8 menit',
    imageUrl: 'https://images.unsplash.com/photo-1592982537447-6f2aa0c8cb08?w=800&q=80',
    content: `Pemupukan berimbang adalah kunci keberhasilan budidaya padi sawah. Berikut panduan lengkapnya:\n\n**1. Pupuk Dasar (Sebelum Tanam)**\nBerikan pupuk organik (kompos/pupuk kandang) sebanyak 2-3 ton/ha. Ini akan memperbaiki struktur tanah dan meningkatkan kapasitas tanah menahan air.\n\n**2. Pupuk Susulan Pertama (7-14 HST)**\nAplikasikan Urea 100 kg/ha + SP-36 100 kg/ha. Sebarkan merata saat kondisi macak-macak (air setinggi 2-3 cm).\n\n**3. Pupuk Susulan Kedua (21-28 HST)**\nBerikan Urea 50 kg/ha + KCl 50 kg/ha. Ini untuk mendukung fase vegetatif (pertumbuhan anakan).\n\n**4. Pupuk Susulan Ketiga (35-40 HST)**\nAplikasikan Urea 50 kg/ha + KCl 50 kg/ha. Pada fase ini tanaman membutuhkan kalium untuk pembentukan malai.\n\n**Tips Penting:**\n- Gunakan Leaf Color Chart (LCC) untuk menentukan kebutuhan nitrogen\n- Jangan memupuk saat hujan deras\n- Pupuk organik harus matang sempurna sebelum diaplikasikan\n- pH tanah optimal untuk padi adalah 5.5-7.0`,
  },
  {
    id: 2, title: 'Mengenal Hama Wereng dan Cara Pencegahannya', type: 'Artikel', category: 'Hama', icon: Bug, readTime: '6 menit',
    imageUrl: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80',
    content: `Wereng Batang Coklat (WBC) adalah hama utama tanaman padi yang bisa menyebabkan kerugian besar.\n\n**Ciri-ciri Serangan:**\n- Tanaman menguning dari pangkal batang\n- Tampak embun jelaga pada daun\n- Tanaman rebah (hopperburn) pada serangan berat\n- Terdapat serangga kecil berwarna coklat di pangkal batang\n\n**Siklus Hidup:**\nWereng betina meletakkan telur di dalam jaringan pelepah daun. Satu betina dapat menghasilkan 100-300 telur. Siklus hidup lengkap sekitar 25-30 hari.\n\n**Pencegahan:**\n1. Gunakan varietas tahan wereng (Inpari 13, Ciherang, Mekongga)\n2. Atur jarak tanam 25x25 cm untuk sirkulasi udara\n3. Hindari penggunaan insektisida piretroid (mematikan musuh alami)\n4. Terapkan pengairan berselang (intermittent irrigation)\n5. Pasang lampu perangkap untuk monitoring populasi\n\n**Pengendalian:**\n- Semprotkan insektisida BPMC atau fipronil pada pangkal batang\n- Gunakan agen hayati Beauveria bassiana\n- Lepaskan predator alami: laba-laba, kumbang coccinella`,
  },
  {
    id: 3, title: 'Irigasi Tetes: Solusi Hemat Air untuk Lahan Kering', type: 'Artikel', category: 'Irigasi', icon: Droplets, readTime: '7 menit',
    imageUrl: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?w=800&q=80',
    content: `Irigasi tetes adalah metode pemberian air langsung ke zona perakaran tanaman melalui emitter/dripper.\n\n**Keuntungan Irigasi Tetes:**\n- Hemat air hingga 50-70% dibanding irigasi konvensional\n- Mengurangi gulma karena hanya area perakaran yang basah\n- Dapat dikombinasikan dengan fertigasi (pupuk cair)\n- Mengurangi risiko penyakit karena daun tidak basah\n\n**Komponen Utama:**\n1. **Sumber air** — sumur, tangki, atau saluran\n2. **Filter** — saringan pasir atau disk filter\n3. **Mainline** — pipa utama PVC 2-3 inch\n4. **Lateral** — selang PE 16mm\n5. **Emitter/Dripper** — debit 2-4 liter/jam\n\n**Pemasangan Sederhana:**\n1. Hubungkan tangki air (elevasi 1-2 meter) ke filter\n2. Sambungkan ke pipa utama lalu ke lateral\n3. Pasang dripper sesuai jarak tanam\n4. Atur jadwal penyiraman: pagi dan sore, 15-30 menit\n\n**Cocok untuk:**\nCabai, tomat, melon, semangka, stroberi, dan tanaman hortikultura lainnya.`,
  },
  {
    id: 4, title: 'Kesejahteraan Petani: Tren Positif NTP Lampung 2026', type: 'Berita', category: 'Ekonomi', icon: TrendingUp, readTime: '4 menit',
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80',
    link: 'https://www.lampungprov.go.id/detail-post/ntp-lampung-mei-2026-naik-menjadi-128-01-kesejahteraan-petani-terus-menguat',
    content: `Nilai Tukar Petani (NTP) merupakan salah satu indikator utama yang mengukur tingkat kesejahteraan petani. Pada bulan Mei 2026, NTP Provinsi Lampung kembali menunjukkan tren positif dengan kenaikan menjadi 128,01.\n\n**Apa Makna Kenaikan NTP?**\nAngka NTP di atas 100 menandakan bahwa indeks harga yang diterima petani (dari penjualan hasil panen) lebih besar dibandingkan indeks harga yang harus dibayar petani (untuk kebutuhan konsumsi keluarga maupun biaya produksi). Dengan kata lain, daya beli petani meningkat.\n\n**Faktor Pendorong Peningkatan:**\n1. **Stabilitas Harga Komoditas**: Harga gabah dan tanaman hortikultura yang stabil di pasaran.\n2. **Program Bantuan Pemerintah**: Dukungan pupuk subsidi dan benih unggul dari Dinas Pertanian menekan biaya produksi.\n3. **Efisiensi Rantai Pasok**: Berkurangnya ketergantungan pada tengkulak yang membuat margin petani lebih besar.\n\n**Dampak Lanjutan:**\nKenaikan kesejahteraan ini memotivasi petani untuk terus berinovasi, menggunakan teknologi tepat guna (seperti aplikasi Tani.Smart), serta berinvestasi pada alat-alat pertanian modern demi produktivitas di masa depan.`,
  },
  {
    id: 5, title: 'Program Unggulan Dinas Tanaman Pangan & Hortikultura', type: 'Artikel', category: 'Program', icon: Handshake, readTime: '5 menit',
    imageUrl: 'https://images.unsplash.com/photo-1595801968843-15794625fc96?w=800&q=80',
    link: 'https://dinastph.lampungprov.go.id/',
    content: `Dinas Tanaman Pangan dan Hortikultura (DTPH) terus meluncurkan program strategis demi mendukung ketahanan pangan nasional dan kesejahteraan petani.\n\n**Fokus Utama Program:**\n\n**1. Bantuan Sarana Produksi (Saprodi)**\nPenyaluran bibit bersertifikat, pupuk berkualitas, dan alat mesin pertanian (Alsintan) seperti traktor dan pompa air kepada kelompok tani aktif.\n\n**2. Pengembangan Kawasan Hortikultura Berbasis Korporasi**\nMembentuk sentra-sentra komoditas unggulan (seperti kawasan cabai, bawang merah, dan buah-buahan tropis) yang dikelola dengan sistem korporasi agar skala ekonominya lebih menguntungkan.\n\n**3. Penyuluhan & Pendampingan Digital**\nMengintensifkan peran penyuluh pertanian lapangan (PPL) dan mengintegrasikan teknologi informasi agar petani dapat dengan mudah mengakses pasar, prakiraan cuaca, dan informasi harga terkini.\n\n**Cara Mengakses Program:**\nPetani dihimbau untuk tergabung dalam Kelompok Tani (Poktan) yang terdaftar di Simluhtan agar dapat menerima pendampingan dan fasilitasi dari pemerintah setempat.`,
  },
  {
    id: 6, title: 'Model Bisnis Kelompok Tani: Sinergi untuk Untung Bersama', type: 'Artikel', category: 'Manajemen', icon: Users, readTime: '6 menit',
    imageUrl: 'https://images.unsplash.com/photo-1599839619722-39751411ea63?w=800&q=80',
    link: 'https://www.pertanian.go.id/',
    content: `Kelompok Tani (Poktan) bukan sekadar wadah kumpul-kumpul, melainkan sebuah entitas bisnis yang strategis jika dikelola dengan benar.\n\n**Mengapa Kelompok Tani Penting?**\nSecara individu, petani seringkali memiliki posisi tawar yang lemah di hadapan pembeli (tengkulak) dan pemasok sarana pertanian. Melalui Poktan, skala ekonomi menjadi lebih besar.\n\n**Model Bisnis & Keuntungan:**\n\n**1. Pembelian Kolektif (Joint Purchasing)**\nDengan membeli pupuk, bibit, atau pestisida secara grosir atas nama kelompok, harga yang didapat jauh lebih murah dibandingkan membeli secara eceran.\n\n**2. Pemasaran Kolektif (Joint Marketing)**\nHasil panen dari seluruh anggota dikumpulkan dan disortir berdasarkan kualitas (grading). Dengan volume yang besar, Poktan dapat langsung menjalin kontrak dengan pabrik, pasar swalayan, atau eksportir tanpa perantara tengkulak.\n\n**3. Koperasi & Simpan Pinjam**\nPoktan yang sudah mapan sering berkembang menjadi Koperasi Unit Desa (KUD) atau Koperasi Pertanian. Ini memungkinkan petani mendapatkan pinjaman modal kerja dengan bunga yang sangat rendah.\n\n**4. Pengelolaan Alat Mesin Pertanian (UPJA)**\nAlat berat seperti traktor atau mesin panen (combine harvester) harganya mahal. Melalui Poktan, alat ini bisa dibeli bersama atau mendapat bantuan pemerintah, lalu disewakan ke anggota dengan tarif bersahabat.`,
  },
];
